[package]
name = "ludum-dare-45"
version = "0.1.0"
authors = ["pc <paraxite@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = "0.7"
lazy_static = "1.4"
rayon = "1.2"